server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_management_db
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma PowerUp FoodCourt Hexagonal Microservices"
appVersion: "1.0.0"

users:
  service:
    url: "http://localhost:8081/api/v1"

jwt:
  secret-key: mi-clave-secreta-personalizada-de-32-bytes
