server:
  port: 8082

#spring:
  #datasource:
    #url: jdbc:mysql://localhost:3306/rest_management_db
    #username: root
    #password: 1234

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db-plazoleta.cplqdirvtijo.us-east-2.rds.amazonaws.com:3306/rest_management_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma PowerUp FoodCourt Hexagonal Microservices"
appVersion: "1.0.0"

users:
  service:
    url: "http://localhost:8081/api/v1"

jwt:
  secret-key: mi-clave-secreta-personalizada-de-32-bytes

twilio:
  accountSid: "ACec312272a2bf3820307ff33b2adfc920"
  authToken: "4bc6c3684acd18a9ed998bdef1895721"
  phoneNumber: "+13613149580"
